# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f0bb5fdac2635867e25f003b9d175920b4c1b043c9fbf73c52487f437f7172384e5d13be17272e23e31c20ba7cb336d6c802cf547d78495ad4db5837b85d7f5

test:
  secret_key_base: 3793c175a619cb60ac30c3986555c29f3bec1267dc0dad12be05899e2870fcea671fee5348436db816e56be4298dbe5fcc76f6eb9c87ef4b14003cb2da7ce1b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
